# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "2aee5932fa1138969056b5bf6fad2f34941f249e";
    sha256 = "0x0n9bz24vym5j30z6gyi9n3rvv441kb2iqb5x3bvkkdalfr11k5";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "fbf9c2762241be3f004d45b9a32b7bfd6ea136a8";
    sha256 = "10lkp39rz21lawb5r93d6w679gdyfgfp7lkcxyg7lm1i2kyp11kl";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "45c823b8af409f82fa35fd5e1f6a7c9a06fe3137";
    sha256 = "1pl3cs6v4b4l3jk7kifni7sc7jn64alpbkwlh12vwd78knqkqmhf";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "40f8087c815403d64e3dd4044411022cc4bedd5b";
    sha256 = "0vrnl0ha6fp6lb3ic9zd37pbab975s9ghcnw7i0wnfasdhb4pvip";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "5bdef9939b483435a61aa91a6422c1a9852127b4";
    sha256 = "0bpzk9k6m3b3d1wv8gfiidbzazqm05afw9hvmcql28a0hrvrdlvv";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "97eafdb8852c52beeedcf49e1c8d16e4b559d331";
    sha256 = "09b4k8152fbwynmyrbbpssxgzrdzcv5difq33a23dz5vhp83ldw0";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "5bd1d25bf33ad63093dfd949435bc92d6d722a75";
    sha256 = "0xd4d24ks21hclkhp9z9czb2phcfiq23z7f9hjhxlxjwf9dpz99p";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p";
    rev = "8768d4dadcd55de1c23a0056a9b3facdd55c9bbb";
    sha256 = "1ymmsr5w5l1dp6h4s87ff8jlbir44a4d69if2z7ijg8k73h7x3m1";
    fetchSubmodules = true;
  };

  libplum = pkgs.fetchgit {
    url = "https://github.com/logos-storage/nim-libplum";
    rev = "189a4984d15f0c60780d6ea5a2ab46bbf6a350f8";
    sha256 = "0nllnpl4mdi58hla0hmx35bkbjmvz4q79wbdmz01vg3qwdnq1r50";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "f156ed72554d16e925ed654833e7f37e8c8e7f8f";
    sha256 = "0x5laxi1sd5z3ribzp6s8kip1hbr5c0jb2lj8vg3qgk0kjr9g7da";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "b56bfb8656bd135f0be17d4da95680e86f71e8b4";
    sha256 = "0zl8hazcmb3mz0wr48dvs6ani9cy7si1i9x6f183n4cmvkrr9flb";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "b3dbc9c4d08e58c5b7bfad6dc7ef2ee52f2f4c08";
    sha256 = "1v4rz42lwcazs6isi3kmjylkisr84mh0kgmlqycx4i885dn3g0l4";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "a671c6d497c7028ed7390b2d5a80c7b62138c586";
    sha256 = "1i7nid50smfmxvc0zc5cp2xd227ll11r7y261bbj769gpd9bz0ax";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "4e1ccd554777e4f9f790176bcffd8009a75fd2b7";
    sha256 = "09q9gcnil4y7wcq9sgdnnrs8b25x1am84mrcljqjcwhm0apy8mb2";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b5473564e80a4908cf6c5a038e4c4a6ca7de2223";
    sha256 = "09abpya7mvcaymxf0n2sc122rq4jkwg9kpis8xyc4z3fx3x3znxk";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "0e601977e5ac8766dbf39fa53b94f908b9cb4753";
    sha256 = "0acix676zivbmn1gzif4mr4gzgipyq7qx1ndq9a4a7l1vvvk9m19";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "4c7252fcd27f72d523e498fba5cf757d101cc3aa";
    sha256 = "125x1szj6cs97ilc4ahq4grlahlfkqcrhi8h76rv5zkj9j66kw9x";
    fetchSubmodules = true;
  };

  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "19701632b4f287b3012a5e435a9d829b0f66c605";
    sha256 = "1k3143m3w57dfnb4nakl1b50qb63gwgjh524461yfkzg642vww9f";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "3f7ec0e0241f0abe6b4d6a124c6a2b6755c4b9da";
    sha256 = "1dik9gmivzbhk111hyh2phb1jgwbgr1x1vivnn8khm81jxmg7ynm";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "7b1d6ed291df9fddcbb5cf16c1968c2b8c6e5a90";
    sha256 = "045x3x4dazg5zsgb2h3qwns6pyzidgxl1m4qmi800qx3ffkalkdy";
    fetchSubmodules = true;
  };

}
