#!/usr/bin/env bash
# Nim-LibP2P-Mix
# Copyright (c) 2026 Status Research & Development GmbH
# Licensed under either of
#  * Apache License, version 2.0 ([LICENSE-APACHE](LICENSE-APACHE))
#  * MIT license ([LICENSE-MIT](LICENSE-MIT))
# at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.

set -euo pipefail

usage() {
  cat <<EOF
Usage:
  $0 <nimble.lock> <output.nix>

The input lock file must already exist.

Example:
  $0 nimble.lock nix/deps.nix
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

LOCKFILE="$1"
OUTFILE="$2"

if [[ ! -f "$LOCKFILE" ]]; then
  echo "error: lock file not found: $LOCKFILE" >&2
  exit 1
fi

command -v jq >/dev/null || { echo "error: jq required" >&2; exit 1; }
command -v nix-prefetch-git >/dev/null || { echo "error: nix-prefetch-git required" >&2; exit 1; }

echo "[*] Generating $OUTFILE from $LOCKFILE"

mkdir -p "$(dirname "$OUTFILE")"

cat > "$OUTFILE" <<'EOF'
# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
EOF

jq -c '
  .packages
  | to_entries
  | sort_by(.key)[]
  | select(.value.downloadMethod == "git")
  # Filter out `nim` itself: nix builds use `pkgs.nim-2_2` from the system,
  # not a fetched Nim source. Including it in deps.nix is redundant and
  # bloats the dependency closure.
  | select(.key != "nim")
' "$LOCKFILE" | while read -r entry; do
  name=$(jq -r '.key' <<<"$entry")
  url=$(jq -r '.value.url' <<<"$entry")
  # Nimble can retain either spelling for the same repository depending on
  # which transitive declaration it visits first. Keep deps.nix deterministic.
  url="${url%.git}"
  rev=$(jq -r '.value.vcsRevision' <<<"$entry")

  echo "  [*] Prefetching $name"

  sha=$(nix-prefetch-git \
    --url "$url" \
    --rev "$rev" \
    --fetch-submodules \
    | jq -r '.sha256')

  cat >> "$OUTFILE" <<EOF
  ${name} = pkgs.fetchgit {
    url = "${url}";
    rev = "${rev}";
    sha256 = "${sha}";
    fetchSubmodules = true;
  };

EOF
done

cat >> "$OUTFILE" <<'EOF'
}
EOF

echo "[+] Wrote $OUTFILE"
